/**
 * au-data.js — Charactry AU Generator Data
 * ══════════════════════════════════════════════════════════════
 * This file is loaded by index.html and story.html to power the
 * AU Generator. You can freely edit, add, or remove entries.
 *
 * Structure:
 *   AU_GENRES      — genre categories shown in the genre dropdown
 *   AU_SETTINGS    — setting concepts per genre
 *   AU_TONES       — narrative tones
 *   AU_HOOKS       — story hooks / central tensions
 *   AU_CONFLICTS   — thematic conflict types
 *   AU_CHAR_ROLES  — roles a character might occupy in an AU
 *   AU_TROPES      — story/narrative tropes to spice up the premise
 *   AU_COLORS      — accent colors per genre for the generated universe card
 *
 * How to add new genres:
 *   1. Add a key to AU_GENRES: { id:'newgenre', label:'New Genre' }
 *   2. Add a matching key to AU_SETTINGS: { newgenre: ['Setting 1', ...] }
 *   3. Optionally add to AU_COLORS: { newgenre: '#hexcolor' }
 * ══════════════════════════════════════════════════════════════
 */

const AU_GENRES = [
  { id:'all',        label:'All Genres'    },
  { id:'fantasy',    label:'Fantasy'       },
  { id:'scifi',      label:'Sci-Fi'        },
  { id:'modern',     label:'Modern'        },
  { id:'horror',     label:'Horror'        },
  { id:'historical', label:'Historical'    },
  { id:'romance',    label:'Romance'       },
  { id:'action',     label:'Action'        },
  { id:'mystery',    label:'Mystery'       },
  { id:'slice',      label:'Slice of Life' },
  { id:'mythology',  label:'Mythology'     },
  { id:'sports',     label:'Sports'        },
  { id:'apocalypse', label:'Apocalypse'    },
  { id:'supernatural',label:'Supernatural' },
];

const AU_SETTINGS = {
  fantasy: [
    'Feudal Magic Kingdom',
    'Fae Court Intrigue',
    'Dragon Empire',
    'Enchanted Academy',
    'Elven Warfront',
    'Cursed Bloodline',
    'Ancient Prophecy',
    'Floating Sky Islands',
    'Underground Dwarf Citadel',
    'Haunted Forest Kingdom',
    'Fallen Angel Hierarchy',
    'Demon Lord's Court',
    'Crystal Mage Tower',
    'Rival Wizard Guilds',
    'Forbidden Magic Underground',
    'Holy Inquisition AU',
    'Shapeshifter Clans',
    'Necromancer Kingdom',
    'Monster Court',
    'Divine Realm Politics',
  ],
  scifi: [
    'Space Colony Fleet',
    'Megacity Dystopia',
    'AI Uprising',
    'Galactic Senate',
    'Cyberpunk Underground',
    'Time-Fractured Reality',
    'Alien Diplomacy',
    'Void Station',
    'Generation Ship',
    'Rogue AI Rebellion',
    'Terraforming Colony',
    'Mind Upload Society',
    'Black Market Tech Ring',
    'Post-Singularity World',
    'Interstellar War',
    'Corporate Oligarchy',
    'Planet-Breaker War',
    'Space Pirate Syndicate',
    'Cryosleep Awakening',
    'Reality Simulation',
  ],
  modern: [
    'Celebrity Life',
    'Underground Fight Ring',
    'Secret Agency',
    'Prestigious Academy',
    'Heist Crew',
    'Street Racing Circuit',
    'Idol Industry',
    'Rival Coffee Shops',
    'Startup Culture',
    'Reality TV Show',
    'High Society Gala',
    'Underground Art Scene',
    'Social Media Influencer War',
    'Corporate Espionage',
    'Hospital Drama',
    'Law Firm Rivalry',
    'Fashion Industry',
    'Organized Crime Family',
    'College Roommates',
    'Graffiti Artist Scene',
  ],
  horror: [
    'Haunted Estate',
    'Cult Survivor',
    'Eldritch Coastal Town',
    'Plague City',
    'Body Horror Lab',
    'Paranormal Investigators',
    'Gothic Carnival',
    'Deep Sea Station',
    'Slasher Summer Camp',
    'Cursed Artifact Museum',
    'Doomsday Cult',
    'Liminal Space Hotel',
    'Found Footage Investigation',
    'Demon Possession Arc',
    'Supernatural Orphanage',
    'Wax Museum Nightmare',
    'The Backrooms',
    'Haunted Video Game',
    'Wendigo Forest',
    'Creepypasta Universe',
  ],
  historical: [
    'Warring States China',
    'Victorian Aristocracy',
    'Samurai Era Japan',
    'Pirate Golden Age',
    'Roman Senate',
    'Silk Road Merchants',
    'Medieval Court',
    'Renaissance Guild',
    'French Revolution',
    'Egyptian Pharaoh Court',
    'Viking Raid Fleet',
    'Ottoman Empire',
    'Aztec Empire',
    'Cold War Spies',
    'Wild West Frontier',
    'Roaring Twenties',
    'World War Resistance Fighter',
    'Spartan War Training',
    'Byzantine Court Intrigue',
    'Industrial Revolution Factory',
  ],
  romance: [
    'Rivals to Lovers',
    'Fake Dating',
    'Second Chance',
    'Forced Proximity',
    'Enemies with History',
    'Slow Burn Academy',
    'Royal Arrangement',
    'Coffee Shop Meet',
    'Pen Pal AU',
    'Time Loop Romance',
    'Soulmate Mark AU',
    'Amnesia Arc',
    'Forbidden Love',
    'Arranged Marriage',
    'Love Triangle',
    'Secret Admirer',
    'Childhood Friends',
    'Celebrity × Normal Person',
    'Boss × Employee',
    'Holiday Stuck Together',
  ],
  action: [
    'Bounty Hunter Circuit',
    'Underground Arena',
    'Heist Syndicate',
    'Revolution Movement',
    'Monster Hunting Guild',
    'Assassin Contract',
    'Road Trip Chaos',
    'Sports Rivalry',
    'Prison Break',
    'Mercenary Company',
    'Vigilante Justice',
    'Special Forces Unit',
    'Treasure Hunt',
    'Car Chase Network',
    'Street Gang Territory War',
    'Death Race Circuit',
    'Gladiator Arena',
    'Spy Network',
    'Parkour Crew',
    'Double Agent Game',
  ],
  mystery: [
    'Detective Agency',
    'Cold Case Reopened',
    'Murder in a Sealed Room',
    'Conspiracy Thriller',
    'Missing Person Investigation',
    'Unreliable Narrator',
    'Blackmail Chain',
    'Secret Society Unraveling',
    'Small Town Secrets',
    'True Crime Podcast',
    'The Witness',
    'Corporate Cover-Up',
    'Art Theft Ring',
    'Locked Room Mystery',
    'Ghost Who Remembers Their Murder',
    'Corrupt Police Department',
    'Identity Theft',
    'Historical Crime Solved',
    'Undercover Investigation',
    'The Alibi',
  ],
  slice: [
    'Cozy Bakery',
    'Small Coastal Town',
    'Farming Village',
    'Student Apartment',
    'Community Garden',
    'Local Band',
    'Bookstore Friends',
    'Neighborhood Watch',
    'Summer Festival',
    'Rainy Season',
    'Grocery Store Staff',
    'Late Night Diner',
    'Shared House',
    'Craft Fair Vendors',
    'Library Study Sessions',
    'Animal Shelter Volunteers',
    'Indie Game Dev Team',
    'Knitting Circle',
    'Rooftop Garden',
    'Vintage Shop',
  ],
  mythology: [
    'Greek Pantheon Drama',
    'Norse Ragnarok',
    'Egyptian Underworld',
    'Japanese Yokai World',
    'Hindu Cosmic War',
    'Celtic Fairy Realm',
    'Aztec Sun Court',
    'Chinese Heavenly Court',
    'Mesopotamian City-States',
    'Slavic Forest Spirits',
    'Polynesian Ocean Gods',
    'African Trickster Tales',
    'Arthurian Legend',
    'Roman Gods Modern AU',
    'Olympus High School',
    'Valhalla After Life',
    'Underworld Bureaucracy',
    'Mortal Champion',
    'Fallen Deity',
    'Myth Reborn',
  ],
  sports: [
    'Pro Basketball Rivalry',
    'Underground Skateboarding',
    'Olympic Training Arc',
    'Amateur Boxing Circuit',
    'School Football Drama',
    'E-Sports Tournament',
    'Fencing Academy',
    'Swimming Team',
    'Ice Skating Competition',
    'Baseball Season',
    'Horse Racing',
    'Martial Arts Tournament',
    'Cycling Tour',
    'Tennis Doubles',
    'Soccer Transfer Season',
    'Wrestling Circuit',
    'Track and Field',
    'Snowboarding Crew',
    'Volleyball Beach Season',
    'Archery Competition',
  ],
  apocalypse: [
    'Zombie Collapse',
    'Nuclear Wasteland',
    'Viral Pandemic',
    'AI Takeover',
    'Climate Collapse',
    'Alien Invasion Survivors',
    'Solar Flare Aftermath',
    'Water Wars',
    'Fungal Overgrowth',
    'Magnetic Pole Shift',
    'Underground Bunker Society',
    'Sea Level Rise Arks',
    'Nanite Plague',
    'God Left the World',
    'The Last City',
    'Radiation Desert',
    'Cannibal Wasteland',
    'Time Fracture End Times',
    'Monster Emergence',
    'Slow Societal Collapse',
  ],
  supernatural: [
    'Urban Witch Coven',
    'Vampire Night Court',
    'Werewolf Pack Politics',
    'Demon and Angel Conflict',
    'Ghost Detective',
    'Necromancer Student',
    'Siren Coast Town',
    'Oracle Academy',
    'Familiar Bond',
    'Exorcist Crew',
    'Haunted City',
    'Reaper Office',
    'Soul Trader Market',
    'Witch Trial Survivor',
    'Shapeshifter High School',
    'Curse Breaker',
    'Shadow Walker',
    'Blood Magic Underground',
    'Elemental Chosen',
    'Interdimensional Hunter',
  ],
};

const AU_TONES = [
  'Dark & Gritty',
  'Hopeful & Uplifting',
  'Bittersweet',
  'Comedic',
  'Epic & Grand',
  'Intimate & Character-Driven',
  'Tense & Thriller',
  'Mysterious & Slow Burn',
  'Melancholic',
  'Absurdist',
  'Romantic',
  'Tragic',
  'Satirical',
  'Whimsical',
  'Bleak',
  'Cozy',
  'Chaotic',
  'Nostalgic',
  'Tense but Hopeful',
  'Morally Complex',
];

const AU_HOOKS = [
  'A secret that could destroy everything',
  'An impossible choice between loyalty and truth',
  'Two people who shouldn\'t trust each other have to',
  'The past won\'t stay buried',
  'Power comes at a price no one expected',
  'The rules of this world are about to break',
  'Someone is lying — but no one knows who',
  'The only way out is through each other',
  'A debt that can never be repaid',
  'The thing they feared becoming is what they\'ve already become',
  'There\'s only one way to fix this, and it\'s going to hurt',
  'They were never supposed to survive',
  'The truth is worse than the lie',
  'Protecting someone means destroying another',
  'The world ended. They\'re still here',
  'The closer they get, the more dangerous it becomes',
  'Everything they built is built on a lie',
  'The person they need most is the one they can\'t trust',
  'There\'s a before and an after — and they lived both',
  'Running was never the answer',
];

const AU_CONFLICTS = [
  'Us vs Them',
  'Internal vs External',
  'Love vs Duty',
  'Survival vs Morality',
  'Freedom vs Safety',
  'Identity vs Expectation',
  'Loyalty vs Truth',
  'Power vs Humanity',
  'Past vs Future',
  'Isolation vs Connection',
  'Order vs Chaos',
  'Ambition vs Integrity',
  'Trust vs Betrayal',
  'Hope vs Despair',
  'Sacrifice vs Selfishness',
];

const AU_CHAR_ROLES = [
  'The reluctant hero',
  'The unlikely villain',
  'The one who knows the truth',
  'Someone with everything to lose',
  'The architect of change',
  'The one who breaks the cycle',
  'A witness to the fall',
  'The reluctant chosen one',
  'The betrayer who didn\'t mean to',
  'The one left behind',
  'The protector who can\'t protect themselves',
  'The double agent',
  'The voice of reason no one listens to',
  'The wildcard',
  'The one everyone underestimates',
  'The last survivor',
  'The weapon that became a person',
  'The idealist in a cynical world',
  'The cynic who still hopes',
  'The one trying to hold everyone together',
];

const AU_TROPES = [
  'Found Family',
  'Enemies to Lovers',
  'Chosen One (Reluctant)',
  'Dark Mirror Character',
  'Last of Their Kind',
  'Betrayal Arc',
  'Redemption Arc',
  'Revenge Arc',
  'Identity Reveal',
  'Power Awakening',
  'Sacrifice Play',
  'Time Loop',
  'Memory Loss',
  'Fake Relationship',
  'Secret Identity',
  'Mentor Death',
  'Villain Was Right',
  'Villain Was Right (About the Wrong Things)',
  'The Fall',
  'Pyrrhic Victory',
];

const AU_COLORS = {
  fantasy:     '#a78bfa',
  scifi:       '#34d399',
  modern:      '#60a5fa',
  horror:      '#f87171',
  historical:  '#fbbf24',
  romance:     '#f9a8d4',
  action:      '#fb923c',
  mystery:     '#818cf8',
  slice:       '#86efac',
  mythology:   '#fcd34d',
  sports:      '#38bdf8',
  apocalypse:  '#ef4444',
  supernatural:'#c084fc',
  all:         '#a78bfa',
};

// Make available globally
if (typeof window !== 'undefined') {
  window.AU_GENRES     = AU_GENRES;
  window.AU_SETTINGS   = AU_SETTINGS;
  window.AU_TONES      = AU_TONES;
  window.AU_HOOKS      = AU_HOOKS;
  window.AU_CONFLICTS  = AU_CONFLICTS;
  window.AU_CHAR_ROLES = AU_CHAR_ROLES;
  window.AU_TROPES     = AU_TROPES;
  window.AU_COLORS     = AU_COLORS;
}